apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-analyzer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-analyzer
  template:
    metadata:
      labels:
        app: image-analyzer
    spec:
      containers:
      - name: image-analyzer
        image: gcr.io/speced/image-analyzer:v1
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: speced